ALTER TABLE public.testimonials
  ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'Buyer',
  ADD COLUMN IF NOT EXISTS location TEXT DEFAULT '';

ALTER TABLE public.success_stories
  ADD COLUMN IF NOT EXISTS category TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS story_type TEXT NOT NULL DEFAULT 'Buy',
  ADD COLUMN IF NOT EXISTS location TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS cta_text TEXT DEFAULT 'View Story',
  ADD COLUMN IF NOT EXISTS images JSONB NOT NULL DEFAULT '[]'::jsonb;